version: '3.8'

services:
  postgres:
    image: postgres
    container_name: booksmart-db
    environment:
      - POSTGRES_USER=booksmart
      - POSTGRES_PASSWORD=booksmart
      - POSTGRES_DB=booksmart
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    command: 
      - "sh"
      - "/docker-entrypoint-initdb.d/init-db.sh"

volumes:
  postgres_data:
