[build]
  command = "npm run build"
  publish = ".next"

[context.production]
  command = "npm run build"
  environment = {
    DATABASE_URL = "${DATABASE_URL}",
    NEXTAUTH_URL = "${NEXTAUTH_URL}",
    NEXTAUTH_SECRET = "${NEXTAUTH_SECRET}",
    NEXT_PUBLIC_API_URL = "${NEXT_PUBLIC_API_URL}",
    NEXT_PUBLIC_APP_URL = "${NEXT_PUBLIC_APP_URL}",
    OPENAI_API_KEY = "${OPENAI_API_KEY}"
  }

[[redirects]]
  from = "/"
  to = "/dashboard"
  status = 301
