[build]
  command = "npm ci && npm run build"
  publish = ".next"
  base = "/"
  cache = [
    "node_modules",
    ".next",
    "node_modules/.cache",
    "node_modules/.vite"
  ]

[dev]
  command = "npm run dev"
  port = 3000

[build.environment]
  DATABASE_URL = "${DATABASE_URL}"
  NEXTAUTH_URL = "https://booksmart.windsurf.build"
  NEXTAUTH_SECRET = "${NEXTAUTH_SECRET}"
  NEXT_PUBLIC_API_URL = "https://booksmart.windsurf.build/api"
  NEXT_PUBLIC_APP_URL = "https://booksmart.windsurf.build"
  OPENAI_API_KEY = "${OPENAI_API_KEY}"

[[redirects]]
  from = "/"
  to = "/dashboard"
  status = 301
